config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :nacebel, :request
  # Begin here
  root 'home#index'

  # Routes for request
  get 'request/new'
  post 'request/new', to: 'request#create'
  get 'request/show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/nacebel.rb
class Nacebel < ApplicationRecord
    has_many :request_nacebel
    has_many :requests, through: :request_nacebel
end

app/models/request.rb
class Request < ApplicationRecord
    has_many :request_nacebel
    has_many :nacebel, through: :request_nacebel
    belongs_to :user

    validates :annualRevenue, presence: true
    validates :enterpriseNumber, presence: true, length: {minimum: 10, maximum: 10}
    validates :legalName, presence: true   
    
end

app/models/request_nacebel.rb
class RequestNacebel < ApplicationRecord
  belongs_to :request
  belongs_to :nacebel
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :requests
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
        p '#'*20
        p 'test'
        p params
        p '#'*20
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :surname, :address, :phonenumber])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :surname, :address, :phonenumber])
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/nacebel_controller.rb
class NacebelController < ApplicationController

end

app/controllers/request_controller.rb
class RequestController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @requests = Request.all
  end

  def new
  end

  def show
    codes = ""

    @request = Request.find(params["id"])
    @request.nacebel.each do |nacebel|
      if codes != ""
        codes.concat(',')
      end
      codes.concat(nacebel.code)
    end
    to_send =  JSON.parse(@request.to_json)
    to_send["nacebelCodes"] = codes.split(',')
    to_send = to_send.except(:annualRevenue, :enterpriseNumber, :legalName, :naturalPerson, :nacebelCodes)
    response = HTTParty.post("https://staging-gtw.seraphin.be/quotes/professional-liability", :body => to_send.to_json, :headers => {'Content-Type' => 'application/json',  "X-Api-Key" => "fABF1NGkfn5fpHuJHrbvG3niQX6A1CO53ftF9ASD"})
    @proposal = response["data"]
    @request
  end

  def create
    p '---Check values---'
    p request_params
    return redirect_to request_index_path, alert: "annualRevenue cannot be empty" if request_params["annualRevenue"] == ""
    return redirect_to request_index_path, alert: "enterpriseNumber cannot be empty" if request_params["enterpriseNumber"] == ""
    return redirect_to request_index_path, alert: "enterpriseNumber must have 10 characters" if request_params["enterpriseNumber"].length != 10
    return redirect_to request_index_path, alert: "legalName cannot be empty" if request_params["legalName"] == ""
    return redirect_to request_index_path, alert: "annualRevenue cannot be empty" if request_params["naturalPerson"] == ""
    params["request_nacebel"].delete_if {|nacebel| nacebel == "" }
    return redirect_to request_index_path, alert: "request_nacebel cannot be empty" if params["request_nacebel"] == []
    return redirect_to request_index_path, alert: "annualRevenue cannot be empty" if request_params["naturalPerson"] == ""
    
    request = Request.create(request_params)
    if request.id.nil?
      raise "Erreur inattendue de création de la request"
    end
    # Création des liens request <> nabelcode grâce aux IDS
    #paramstoadd = params["request_nacebel"].drop(1)
    CreateLinks(request.id, params["request_nacebel"])
    # Je dois encore ajouter les codes dans le to_send
    to_send =  JSON.parse(request.to_json)
    # Le front bricolé renvoie un vide dans le array qu'on doit retirer
    #request_nacebel = params["request_nacebel"].drop(1)
    #to_send << request_nacebel
    to_send["nacebelCodes"] = params["request_nacebel"]
    #request << request_nacebel
    to_send = to_send.except(:annualRevenue, :enterpriseNumber, :legalName, :naturalPerson, :nacebelCodes)
    response = HTTParty.post("https://staging-gtw.seraphin.be/quotes/professional-liability", :body => to_send.to_json, :headers => {'Content-Type' => 'application/json',  "X-Api-Key" => "fABF1NGkfn5fpHuJHrbvG3niQX6A1CO53ftF9ASD"})
    respond_to do |format|
      if response.success?
        format.html { redirect_to request_path(request.id), notice: "Request was successfully created." }
        format.json { render :json => response}
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    request = Request.find(params["id"])

    RequestNacebel.where(request_id: params["id"]).destroy_all
    Request.find(params["id"]).destroy

    respond_to do |format|
      format.html { redirect_to request_index_url, notice: "Request was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private 
  # Only allow a list of trusted parameters through.
  def request_params
    params.permit(:email, :phonenumber, :name, :surname, :address, :annualRevenue, :enterpriseNumber, :legalName, :naturalPerson, :user_id)
  end

  def CreateLinks(requestid, nacebelToAdd)
    nacebelToAdd.each do |nacebel|
      nacebelid = Nacebel.find_by(code: nacebel).id
      RequestNacebel.create(request_id: requestid, nacebel_id: nacebelid)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_helper.rb
module FormHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/nacebel_helper.rb
module NacebelHelper
end

app/helpers/result_helper.rb
module ResultHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'AssuranceApp', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
        <li class="nav-item">
        <li class="nav-item">
            <%= link_to 'Faites votre simulation', request_new_path , class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to 'Vos propositions', request_index_path, class:"nav-link" %>
        </li>
            <%= link_to 'Sign out', destroy_user_session_path,  data: { "turbo-method": :delete }, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
        </li>
        <% else %>
        <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to 'Sign in', new_user_session_path, class:"nav-link" %>
        </li>
        <% end %>
        
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Fix your RC</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>AssuranceApp</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'home/header' %>
    
    <div class="container">
    <br/>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <br/>
      <%= yield %>
    </div>
  </body>
</html>

app/views/request/index.html.erb
<table class="table table-striped table-hover">
  <thead class="table-dark">
    <tr>
      <th scope="col">AnnualRevenue</th>
      <th scope="col">EnterpriseNumber</th>
      <th scope="col">LegalName</th>
      <th scope="col">NaturalPerso</th>
      <th scope="col">nacebelCodes</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  <% @requests.each do |request| %>
  <% if request.user == current_user %>
    <tr>
      <%= render request %>
      <td><%= button_to 'Delete', request, method: :delete, class:"btn btn-outline-danger btn-sm" %>
            <%= button_to 'Show', request, method: :get, class:"btn btn-secondary" %></td>
    </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/request/new.html.erb
Merci de remplir ses informations pour pouvoir recevoir votre offre personnalisée d'assurance !
<%= form_with model: @request do |form| %>
  <div class="form-group">
    <%= form.text_field :email, class:"form-control", placeholder:"Email", value: current_user.email, :readonly => true %>
  </div>
  <br/>
  <div class="form-group">
    <%= form.text_field :name, class:"form-control", placeholder:"name", value: current_user.name, :readonly => true %>
  </div>
  <br/>
  <div class="form-group">
    <%= form.text_field :surname, class:"form-control", placeholder:"surname", value: current_user.surname, :readonly => true %>
  </div>
  <br/>
  <div class="form-group">
    <%= form.text_field :phonenumber, class:"form-control", placeholder:"phonenumber", value: current_user.phonenumber, :readonly => true %>
  </div>
  <br/> 
  <div class="form-group">
    <%= form.text_field :address, class:"form-control", placeholder:"address", value: current_user.address, :readonly => true %>
  </div>
  <br/>
  <p>Info pour votre assurance</p>
  <br/>
   <div class="form-group">
    <%= form.text_field :annualRevenue, class:"form-control", placeholder:"annualRevenue" %>
  </div>
  <br/>
   <div class="form-group">
    <%= form.text_field :enterpriseNumber, class:"form-control", placeholder:"enterpriseNumber" %>
  </div>
  <br/>
  <div class="form-group">
    <%= form.text_field :legalName, class:"form-control", placeholder:"legalName" %>
  </div>
  <br/>
  <div class="form-group">
    <!--<%= form.select "request_nacebel[]", Nacebel.all.collect { |p| [ p.code, p.id ] }, {:multiple => :multiple, :size => 10} %>-->
    <%= form.select("request_nacebel", Nacebel.all.collect { |p| [ p.code ] },{ :allow_blank => false},
                                   { :multiple => true, :size => 10 }
                                 ) %>
  </div>
  <br/>
  <div class="form-group">
  <!-- <%= form.check_box :naturalPerson, class:"form-control" %>-->
    <%= form.check_box :naturalPerson %>
    <%= form.label :naturalPerson, "naturalPerson" %>
  </div>
  <br/>
  <div class="form-group">
    <%= form.number_field :user_id, id: :request_user_id, class:"form-control", placeholder:"User Id", value: current_user.id, type: :hidden %>
  </div>
  <br/>
  <div>
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/request/show.html.erb
Revenu annuel : <%= @request.annualRevenue %><br/>
Numéro entreprise : <%= @request.enterpriseNumber %><br/>
nom légal : <%= @request.legalName %><br/>
natural person : <%= @request.naturalPerson %><br/>
NacebelCode liés : <%  codes = ""
@request.nacebel.each do |nacebel|
    if codes != "" 
        codes.concat(',')
    end
    codes.concat(nacebel.code)
end %> <%= codes %><br/>
<br/><br/><br/>
<% @proposal %>
Disponibilité : <%= @proposal["available"] %><br/>
Coverage Ceiling : <%= @proposal["coverageCeiling"] %><br/>
Deductibilité : <%= @proposal["deductible"] %><br/>
QuoteId : <%= @proposal["quoteId"] %><br/>
Premium : <br/> <!-- Est-ce que ça sera toujours "grossPremiums" ? -->
    afterDelivery : <%= @proposal["grossPremiums"]["afterDelivery"] %><br/>
    publicLiability : <%= @proposal["grossPremiums"]["publicLiability"] %><br/>
    professionalIndemnity : <%= @proposal["grossPremiums"]["professionalIndemnity"] %><br/>
    entrustedObjects : <%= @proposal["grossPremiums"]["entrustedObjects"] %><br/>
    legalExpenses : <%= @proposal["grossPremiums"]["legalExpenses"] %><br/>

app/views/requests/_request.html.erb
<td><%= request.annualRevenue %></td>
<td><%= request.enterpriseNumber %></td>
<td><%= request.legalName %></td>
<td><%= request.naturalPerson %></td>
<td><%  codes = ""
request.nacebel.each do |nacebel|
    if codes != "" 
        codes.concat(',')
    end
    codes.concat(nacebel.code)
end %> <%= codes %> </td>